version: '3.8'

services:
  image-bed:
    build: .
    container_name: image-bed
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      # 服务器配置
      - SERVER_PORT=8080
      - SERVER_DOMAIN=
      # 数据库配置
      - DB_TYPE=sqlite
      - DB_FILE_PATH=/app/data/image-bed.db
      # 缓存配置
      - CACHE_ENABLE_IMAGE_CACHING=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s